CREATE DATABASE QuanLyThietBi
Go
USE QuanLyThietBi
Go
CREATE TABLE Nhom(
MANHOM INT PRIMARY KEY,
TENNHOM NVARCHAR(200)
)
Go
CREATE TABLE ThietBi(
MATHIETBI INT PRIMARY KEY,
TENTHIETBI NVARCHAR(200),
SOLUONG INT,
DONGIA DECIMAL(18,0),
MANHOM INT
)